#%RAML 1.0 Trait
headers:
  Content-Type:
    description: this header will be used to pass the datatype 
    required: true
    type: string
    enum:
      - Application/json
    example:
      "Application/json"
      