#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        type: !include ../datatypes/healthCheck-dataType.raml
        example: !include ../examples/healthCheck-example.json
          
