#%RAML 1.0 Trait
queryParameters:
  featurName:
    description: This query param will be used to identify feature of API
    required: true
    type: string
    enum:
      - changecontact
    example:
      "changecontact"